import argparse
from datetime import datetime
from pathlib import Path

from create_design_package import design_status_from_opportunity
from forge_image_kernel import create_image_request
from pipeline_contracts import (
    OPPORTUNITY_FILE,
    DESIGN_FILE,
    create_handoff,
    load_json,
    save_json,
    next_id,
)


def now_stamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def csv_list(raw):
    if not raw:
        return []
    if isinstance(raw, list):
        return raw
    return [x.strip() for x in str(raw).split(",") if x.strip()]


def opportunity_already_has_design(opportunity_id, designs):
    for design in designs:
        if design.get("opportunity_id") == opportunity_id and not str(design.get("status", "")).startswith("superseded"):
            return True
    return False


def find_next_opportunity(opportunities, designs, include_weak=True):
    priority = []

    for opp in opportunities:
        opp_id = opp.get("id")

        if not opp_id:
            continue

        if opportunity_already_has_design(opp_id, designs):
            continue

        status = opp.get("status")

        if status == "evidence_backed":
            priority.append(opp)
        elif include_weak and status in {"weak_evidence", "hypothesis_only"}:
            priority.append(opp)

    return priority[0] if priority else None


def build_design_from_opportunity(opportunity):
    title = f"Forge Concept From {opportunity.get('id')}: {opportunity.get('title')}"
    lane = opportunity.get("design_lane", "source-derived design lane")
    style = opportunity.get("design_style", "original trend-safe style")
    emotional_angle = opportunity.get("emotional_angle", "buyer emotion")
    buyer_moment = opportunity.get("buyer_moment", "buyer moment")
    safe_angle = opportunity.get("original_safe_angle", "original non-branded design angle")
    product_fit = opportunity.get("product_fit", [])

    design_concept = (
        f"Original concept based on opportunity {opportunity.get('id')}. "
        f"Design lane: {lane}. Style: {style}. Emotional angle: {emotional_angle}. "
        f"Buyer moment: {buyer_moment}. Safe angle: {safe_angle}. "
        f"No protected IP, no brand names, no celebrity likeness, no copied slogans."
    )

    image_prompt = (
        f"Original print-on-demand design concept. "
        f"Theme/lane: {lane}. Style: {style}. Emotional mood: {emotional_angle}. "
        f"Buyer moment: {buyer_moment}. Product fit: {', '.join(product_fit) if product_fit else 'poster, shirt, mug'}. "
        f"Clean commercial layout, printable composition, cohesive color palette, no logos, no brand names, "
        f"no existing characters, no celebrity likeness, no protected quotes, no watermark, no signature."
    )

    filename_stem = (
        "forge_"
        + str(opportunity.get("id", "opp")).lower().replace("-", "_")
        + "_"
        + "".join(ch.lower() if ch.isalnum() else "_" for ch in str(opportunity.get("title", "concept")))[:60].strip("_")
    )

    return {
        "title": title,
        "design_concept": design_concept,
        "image_prompt": image_prompt,
        "product_fit": product_fit,
        "print_area_notes": "Start with poster-safe composition. Adapt to shirt/mug only after QA confirms simpler layout.",
        "aspect_ratio": "4:5",
        "transparent_background": False,
        "mockup_notes": "Mockup only until evidence, Sentinel, Ledger, and listing gates pass.",
        "filename_stem": filename_stem,
        "copyright_trademark_risk": opportunity.get("copyright_trademark_risk", "unknown"),
        "safety_notes": "Generated by Forge opportunity consumer. Production/listing remains gated by Sentinel, Ledger, Scribe, Publisher, and Overseer.",
    }


def create_design_package_from_opportunity(opportunity):
    designs = load_json(DESIGN_FILE, [])
    gate = design_status_from_opportunity(opportunity)
    draft = build_design_from_opportunity(opportunity)

    design = {
        "id": next_id("DESIGN", designs),
        "type": "design_package",
        "status": gate["status"],
        "opportunity_id": opportunity.get("id"),
        "opportunity_status": opportunity.get("status"),
        "evidence_level": gate["evidence_level"],
        "gate_reason": gate["reason"],
        "title": draft["title"],
        "design_concept": draft["design_concept"],
        "image_prompt": draft["image_prompt"],
        "product_fit": csv_list(draft["product_fit"]),
        "print_area_notes": draft["print_area_notes"],
        "aspect_ratio": draft["aspect_ratio"],
        "transparent_background": draft["transparent_background"],
        "mockup_notes": draft["mockup_notes"],
        "filename_stem": draft["filename_stem"],
        "copyright_trademark_risk": draft["copyright_trademark_risk"],
        "safety_notes": draft["safety_notes"],
        "production_allowed": gate["production_allowed"],
        "listing_allowed": False,
        "created_at": now_stamp(),
    }

    designs.append(design)
    save_json(DESIGN_FILE, designs)

    if design["status"] == "ready_for_ledger":
        handoff = create_handoff(
            from_agent="Forge",
            to_agent="Ledger",
            artifact_type="design_package",
            artifact_id=design["id"],
            summary=f"Forge created design package {design['id']} from {opportunity.get('id')}. Ready for Ledger only; production still false.",
            required_next_action="Ledger may calculate unit economics. Production and listing remain blocked until Ledger PASS.",
            status="ready_for_ledger",
        )
    else:
        handoff = create_handoff(
            from_agent="Forge",
            to_agent="Overseer",
            artifact_type="design_package",
            artifact_id=design["id"],
            summary=f"Forge created concept-only design package {design['id']} from {opportunity.get('id')}. Evidence level: {design.get('evidence_level')}.",
            required_next_action="Collect stronger evidence before Ledger/pricing/production.",
            status="concept_only_blocked_from_production",
        )

    return design, handoff


def create_default_image_request_for_design(design):
    request = create_image_request(
        design_package_id=design["id"],
        provider_id="manual_image_generation",
        subject=f"original print-on-demand design for {design.get('title')}",
        composition="centered commercial composition, clear focal point, balanced negative space, product-safe layout, no clutter",
        style="original trend-safe commercial POD artwork, clean printable design, not copied from any artist or brand",
        color_palette="cohesive limited palette chosen to match the design concept",
        text_rules="No readable text unless explicitly approved in a later Scribe/Sentinel pass. Decorative abstract marks only.",
        product_use="poster-first concept; later adapt to shirt, mug, tote, or sticker after QA",
        aspect_ratio=design.get("aspect_ratio", "4:5"),
        required_elements=[
            "clear focal subject",
            "print-safe composition",
            "cohesive style",
            "no protected references",
        ],
        forbidden_elements=[
            "logos",
            "brand names",
            "TV show references",
            "movie references",
            "game references",
            "anime references",
            "characters",
            "celebrity likeness",
            "protected quotes",
            "watermarks",
            "signatures",
            "readable accidental text",
        ],
        negative_constraints=(
            "No copyrighted characters. No logos. No brand names. No direct pop culture references. "
            "No celebrity likeness. No protected slogans. No watermark. No signature. "
            "No blurry artifacts. No malformed subject. No accidental readable text."
        ),
        quality_bar=(
            "Must look like a clean commercial product design with strong composition, accurate prompt match, "
            "printable spacing, no IP risk, and no accidental text."
        ),
        size="1024x1280",
        seed="none",
        notes="Created automatically by Forge opportunity consumer. Manual generation only; no live upload.",
    )

    return request


def run_forge_on_next_opportunity(include_weak=True):
    opportunities = load_json(OPPORTUNITY_FILE, [])
    designs = load_json(DESIGN_FILE, [])

    opportunity = find_next_opportunity(opportunities, designs, include_weak=include_weak)

    if not opportunity:
        return {
            "status": "no_unprocessed_opportunity",
            "opportunity": None,
            "design": None,
            "handoff": None,
            "image_request": None,
            "message": "No unprocessed opportunity found for Forge.",
        }

    design, handoff = create_design_package_from_opportunity(opportunity)
    image_request = create_default_image_request_for_design(design)

    return {
        "status": "completed",
        "opportunity": opportunity,
        "design": design,
        "handoff": handoff,
        "image_request": image_request,
        "message": "Forge consumed one opportunity and created a design package plus image request.",
    }


def main():
    parser = argparse.ArgumentParser(description="Run Forge on the next unprocessed opportunity.")
    parser.add_argument("--include-weak", choices=["true", "false"], default="true")
    args = parser.parse_args()

    result = run_forge_on_next_opportunity(include_weak=args.include_weak == "true")

    print()
    print("# Forge Opportunity Consumer")
    print()
    print(f"Status: {result['status']}")
    print(result.get("message", ""))

    if result.get("opportunity"):
        print(f"Opportunity: {result['opportunity'].get('id')} / {result['opportunity'].get('title')}")

    if result.get("design"):
        design = result["design"]
        print(f"Design: {design.get('id')}")
        print(f"Design Status: {design.get('status')}")
        print(f"Evidence Level: {design.get('evidence_level')}")
        print(f"Production Allowed: {design.get('production_allowed')}")

    if result.get("image_request"):
        request = result["image_request"]
        print(f"Image Request: {request.get('id')}")
        print(f"Image Request Status: {request.get('status')}")
        print(f"Image Production Allowed: {request.get('production_allowed')}")

    print()


if __name__ == "__main__":
    main()
